"""Shared status constants for browser-agent Zhuque detection."""

BROWSER_AGENT_STATUS_ONLINE = "online"
BROWSER_AGENT_STATUS_OFFLINE = "offline"
BROWSER_AGENT_STATUS_REVOKED = "revoked"
BROWSER_AGENT_STATUSES = {
    BROWSER_AGENT_STATUS_ONLINE,
    BROWSER_AGENT_STATUS_OFFLINE,
    BROWSER_AGENT_STATUS_REVOKED,
}

ZHUQUE_AGENT_JOB_STATUS_PENDING = "pending"
ZHUQUE_AGENT_JOB_STATUS_CLAIMED = "claimed"
ZHUQUE_AGENT_JOB_STATUS_RUNNING = "running"
ZHUQUE_AGENT_JOB_STATUS_MANUAL_REQUIRED = "manual_required"
ZHUQUE_AGENT_JOB_STATUS_COMPLETED = "completed"
ZHUQUE_AGENT_JOB_STATUS_FAILED = "failed"
ZHUQUE_AGENT_JOB_STATUS_EXPIRED = "expired"
ZHUQUE_AGENT_JOB_STATUS_CANCELLED = "cancelled"
ZHUQUE_AGENT_JOB_STATUSES = {
    ZHUQUE_AGENT_JOB_STATUS_PENDING,
    ZHUQUE_AGENT_JOB_STATUS_CLAIMED,
    ZHUQUE_AGENT_JOB_STATUS_RUNNING,
    ZHUQUE_AGENT_JOB_STATUS_MANUAL_REQUIRED,
    ZHUQUE_AGENT_JOB_STATUS_COMPLETED,
    ZHUQUE_AGENT_JOB_STATUS_FAILED,
    ZHUQUE_AGENT_JOB_STATUS_EXPIRED,
    ZHUQUE_AGENT_JOB_STATUS_CANCELLED,
}
ZHUQUE_AGENT_JOB_TERMINAL_STATUSES = {
    ZHUQUE_AGENT_JOB_STATUS_COMPLETED,
    ZHUQUE_AGENT_JOB_STATUS_FAILED,
    ZHUQUE_AGENT_JOB_STATUS_EXPIRED,
    ZHUQUE_AGENT_JOB_STATUS_CANCELLED,
}
